Update GLM-5.md to refer to atom-dev docker container
Fixes the following bug that happens currently with https://hub.docker.com/layers/rocm/atom/latest/images/sha256-6e79a3cb7bca1371b025cc877bfc4afe0d1f5c5976d15d31fb707573969d99ba container, which gives errors as follows:

```docker run -it --network=host --group-add=video   --device /dev/kfd --device /dev/dri --privileged
--ipc=host --cap-add=SYS_PTRACE --security-opt seccomp=unconfined rocm/atom:latest bash

root@cv350-zts-gtu-c9-18:/# python -m atom.entrypoints.openai_server --model zai-org/GLM-5-FP8 -tp 8 --kv_cache_dtype fp8 --port 5678 --server-port 7777
[aiter] import [module_aiter_enum] under /app/aiter-test/aiter/jit/module_aiter_enum.so
[aiter] merge tuned file under model_configs/ and configs/ /app/aiter-test/aiter/configs/bf16_tuned_gemm.csv:/app/aiter-test/aiter/configs/model_configs/gptoss_bf16_tuned_gemm.csv:/app/aiter-test/aiter/configs/model_configs/dsv3_bf16_tuned_gemm.csv
Loading tokenizer from zai-org/GLM-5-FP8...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/ATOM/atom/entrypoints/openai_server.py", line 917, in <module>
    main()
  File "/app/ATOM/atom/entrypoints/openai_server.py", line 905, in main
    tokenizer = AutoTokenizer.from_pretrained(args.model)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 1153, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class TokenizersBackend does not exist or is not currently imported.
```